stack: node 10

branches:
  only:
    - master

cache: node_modules

install:
  - npm install

build: off

test_script:
  - npm test

deploy_script:
  - mkdir dist
  - xcopy src\js dist /E
  - xcopy src\index.html dist /E
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://%GITHUB_TOKEN%:x-oauth-basic@github.com" > "%USERPROFILE%\.git-credentials"
#  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n"
  - dos2unix %USERPROFILE%\.git-credentials
  - more %USERPROFILE%\.git-credentials
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
