# https://www.appveyor.com/docs/lang/nodejs-iojs/
# https://www.appveyor.com/docs/appveyor-yml/
image: ubuntu

stack: node 10

install:
  - npm install

build: off

test_script:
  - npm test

deploy_script:
  - mkdir dist && cp -R src/js src/index.html dist
  - git config --global credential.helper store
  - echo "https://$($env:access_token):x-oauth-basic@github.com\n" > "~/.git-credentials"
  - git subtree push --prefix dist origin gh-pages
